// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsAddRequest(buf []byte, offset flatbuffers.UOffsetT) *AddRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddRequest{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAddRequest(buf []byte, offset flatbuffers.UOffsetT) *AddRequest {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddRequest{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AddRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *AddRequest) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *AddRequest) Title() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func AddRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func AddRequestAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(url), 0)
}
func AddRequestAddTitle(builder *flatbuffers.Builder, title flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(title), 0)
}
func AddRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
