// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package bookmarks

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type AddResponse struct {
	_tab flatbuffers.Table
}

func GetRootAsAddResponse(buf []byte, offset flatbuffers.UOffsetT) *AddResponse {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &AddResponse{}
	x.Init(buf, n+offset)
	return x
}

func GetSizePrefixedRootAsAddResponse(buf []byte, offset flatbuffers.UOffsetT) *AddResponse {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &AddResponse{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func (rcv *AddResponse) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *AddResponse) Table() flatbuffers.Table {
	return rcv._tab
}

func AddResponseStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func AddResponseEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
